name: 테스트 태그 생성
on:
  push:
    branches-ignore:
      - main
jobs:
  update-release-tag:
    name: Update release tag
    runs-on: ubuntu-latest
    steps:
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v6.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Test ${{ steps.generate_release_tag.outputs.next_release_tag }}
          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: false
          prerelease: true